defmodule ConvergerWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :converger

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_converger_key",
    signing_salt: "lyNPY7bc",
    same_site: "Lax"
  ]

  # Client sockets. Frames above the hard cap close the socket with 1009;
  # refused connections (draining) get 503. Per-socket limits are enforced by
  # ConvergerWeb.SocketGuard; on shutdown sockets are drained in batches
  # (ConvergerWeb.Drain). See docs/operations/websocket-limits.md.
  @client_websocket [
    timeout: 60_000,
    max_frame_size: Application.compile_env(:converger, :websocket_max_frame_size, 1_048_576),
    error_handler: {ConvergerWeb.SocketGuard, :handle_error, []}
  ]

  # Deprecated (#23): the pre-v1 legacy socket. Use /socket/converger, the
  # single WebSocket entry point. See ConvergerWeb.Deprecation.
  socket "/socket", ConvergerWeb.UserSocket,
    websocket: @client_websocket,
    longpoll: false,
    drainer: {ConvergerWeb.Drain, :drainer_config, []}

  # Long-polling is the last-resort fallback for networks that block
  # WebSockets (the `phoenix` JS client falls back to it automatically). The
  # native v1 endpoint (/socket/converger/v1) and the SSE stream are routed
  # in ConvergerWeb.Router.
  socket "/socket/converger", ConvergerWeb.ConvergerSocket,
    websocket: @client_websocket,
    longpoll: true,
    drainer: {ConvergerWeb.Drain, :drainer_config, []}

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [:peer_data, session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # GET /health/live and /health/ready for load balancers and Kubernetes.
  # First, so probes are not redirected to HTTPS or logged per request.
  plug ConvergerWeb.Plugs.Health

  # Must run before anything that reads conn.remote_ip (AdminAuth, RateLimit)
  # and before ForceSSL, which only trusts X-Forwarded-Proto from the proxies
  # this plug accepted.
  plug ConvergerWeb.Plugs.TrustedProxies

  # HTTP -> HTTPS redirect + HSTS, configured at runtime (FORCE_SSL, HSTS_*).
  # Runs before Plug.Static so assets are covered too. WebSocket upgrades are
  # dispatched by Phoenix before these plugs; see docs/deployment.md.
  plug ConvergerWeb.Plugs.ForceSSL

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :converger,
    gzip: not code_reloading?,
    only: ConvergerWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :converger
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Origins are resolved on every request (see `cors_origins/0`) so that
  # `CORS_ORIGINS` set in config/runtime.exs takes effect on releases
  # without recompiling.
  plug CORSPlug,
    origin: &__MODULE__.cors_origins/0,
    headers: ["x-channel-token", "x-api-key", "authorization"] ++ CORSPlug.defaults()[:headers]

  plug Plug.Parsers,
    parsers: [:urlencoded, ConvergerWeb.MultipartParser, :json],
    pass: ["*/*"],
    body_reader: {ConvergerWeb.CacheBodyReader, :read_body, []},
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ConvergerWeb.Router

  @doc """
  Returns the allowed CORS origins, read from the `:cors_origins` application
  env at request time (configured via `CORS_ORIGINS` in config/runtime.exs).
  """
  @spec cors_origins() :: [String.t()]
  def cors_origins, do: Application.get_env(:converger, :cors_origins, [])
end
