defmodule ConvergerWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :converger

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_converger_key",
    signing_salt: "lyNPY7bc",
    same_site: "Lax"
  ]

  socket "/socket", ConvergerWeb.UserSocket,
    websocket: true,
    longpoll: false

  socket "/socket/converger", ConvergerWeb.ConvergerSocket,
    websocket: true,
    longpoll: false

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [:peer_data, session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :converger,
    gzip: not code_reloading?,
    only: ConvergerWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :converger
  end

  # Must run before anything that reads conn.remote_ip (AdminAuth, RateLimit).
  plug ConvergerWeb.Plugs.TrustedProxies

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Origins are resolved on every request (see `cors_origins/0`) so that
  # `CORS_ORIGINS` set in config/runtime.exs takes effect on releases
  # without recompiling.
  plug CORSPlug,
    origin: &__MODULE__.cors_origins/0,
    headers: ["x-channel-token", "x-api-key", "authorization"] ++ CORSPlug.defaults()[:headers]

  plug Plug.Parsers,
    parsers: [:urlencoded, ConvergerWeb.MultipartParser, :json],
    pass: ["*/*"],
    body_reader: {ConvergerWeb.CacheBodyReader, :read_body, []},
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ConvergerWeb.Router

  @doc """
  Returns the allowed CORS origins, read from the `:cors_origins` application
  env at request time (configured via `CORS_ORIGINS` in config/runtime.exs).
  """
  @spec cors_origins() :: [String.t()]
  def cors_origins, do: Application.get_env(:converger, :cors_origins, [])
end
