defmodule Converger.Uploads.Storage do
  @moduledoc """
  Behaviour for file storage backends.

  Every callback receives the backend configuration (the `:storage_opts`
  keyword list from `config :converger, Converger.Uploads`) as its first
  argument, so backends hold no global state and are easy to test.

  Keys are opaque, slash separated object names generated by
  `Converger.Uploads` (`<tenant_id>/<attachment_id>`).
  """

  @type config :: keyword()
  @type key :: String.t()

  @doc "Stores `binary` under `key`. Options: `:content_type`."
  @callback put(config, key, binary(), opts :: keyword()) :: :ok | {:error, term()}

  @doc "Reads the object stored under `key`."
  @callback get(config, key) :: {:ok, binary()} | {:error, :not_found | term()}

  @doc "Deletes the object. Deleting a missing object is not an error."
  @callback delete(config, key) :: :ok | {:error, term()}

  @doc """
  Returns a short-lived signed GET URL for the object, or
  `{:error, :unsupported}` when the backend cannot produce one (local disk).

  Options: `:expires_in` (seconds), `:content_type`, `:content_disposition`
  (response header overrides, where the provider supports them).
  """
  @callback signed_get_url(config, key, opts :: keyword()) ::
              {:ok, String.t()} | {:error, :unsupported | term()}

  @doc """
  Returns a presigned upload request a client can use to PUT the object
  directly to the provider (for large files), or `{:error, :unsupported}`.

  The result includes the `:headers` the client must send with the PUT.
  """
  @callback presigned_put_url(config, key, opts :: keyword()) ::
              {:ok, %{method: String.t(), url: String.t(), headers: map()}}
              | {:error, :unsupported | term()}

  @doc "Absolute path on local disk, for backends that store files locally."
  @callback local_path(config, key) :: {:ok, String.t()} | {:error, :unsupported}

  @optional_callbacks local_path: 2
end
