import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * The sidebar is generated from the repository's `docs/` folder (the single
 * source of truth): file order comes from `sidebar_position` front matter,
 * folders from `_category_.json`. New pages and folders (for example
 * `docs/protocol/`) show up automatically.
 *
 * A few long-standing pages live at the root of `docs/` because code, error
 * messages and other docs link to them by path (`docs/deployment.md`,
 * `docs/security.md`, ...). `sidebarItemsGenerator` in `docusaurus.config.ts`
 * moves them into their section without moving the files.
 */
const sidebars: SidebarsConfig = {
  docs: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
